# example partition_options
# it creates two paritions "train" and "val" from the h5 dataset file
# as for a quick test, this only involves 10% of all entries, and frames are loaded
# the batch size is set to maximize the usage of 11-GB VRAM of the GPUs on cluster nodes
# e.g., GTX1080Ti and 2080Ti
# note that the batch size controls the batch loaded to each GPU, thus in parallel setup,
# the effective batch size for training will be this batch size times the number of processes
train:
  metasets:
    OPEP:
      molecules:
      - opep_0000
      - opep_0001
      - opep_0002
      - opep_0004
      - opep_0005
      - opep_0007
      - opep_0008
      - opep_0009
      - opep_0010
      - opep_0012
      - opep_0015
      - opep_0016
      - opep_0017
      - opep_0020
      - opep_0022
      - opep_0025
      - opep_0028
      - opep_0029
      - opep_0030
      - opep_0031
      - opep_0032
      - opep_0034
      - opep_0035
      - opep_0037
      - opep_0038
      - opep_0040
      - opep_0043
      - opep_0044
      - opep_0045
      - opep_0046
      - opep_0047
      - opep_0048
      - opep_0049
      - opep_0050
      - opep_0051
      - opep_0052
      - opep_0053
      - opep_0054
      - opep_0055
      - opep_0056
      - opep_0057
      - opep_0058
      - opep_0060
      - opep_0061
      - opep_0064
      - opep_0065
      - opep_0066
      - opep_0067
      - opep_0068
      - opep_0069
      - opep_0071
      - opep_0073
      - opep_0074
      - opep_0075
      - opep_0076
      - opep_0078
      - opep_0079
      - opep_0082
      - opep_0084
      - opep_0085
      - opep_0086
      - opep_0087
      - opep_0088
      - opep_0089
      - opep_0090
      - opep_0091
      - opep_0092
      - opep_0093
      - opep_0094
      - opep_0096
      - opep_0097
      - opep_0100
      - opep_0101
      - opep_0102
      - opep_0103
      - opep_0104
      - opep_0105
      - opep_0106
      - opep_0107
      - opep_0108
      - opep_0109
      - opep_0110
      - opep_0111
      - opep_0112
      - opep_0115
      - opep_0116
      - opep_0117
      - opep_0118
      stride: 100
    CATH:
      molecules:
      - cath_1b43A02
      - cath_1bl0A02
      - cath_1c75A00
      - cath_1d3yA01
      stride: 100
  batch_sizes:
    OPEP: 37
    CATH: 8
  subsample_random_seed: 42 # can be anything. Keeping it unchanged allows reproducibility
  max_epoch_samples:
val:
  metasets:
    OPEP:
      molecules:
      - opep_0003
      - opep_0006
      - opep_0011
      - opep_0013
      - opep_0014
      - opep_0018
      - opep_0019
      - opep_0021
      - opep_0023
      - opep_0024
      - opep_0026
      - opep_0027
      - opep_0033
      - opep_0036
      - opep_0039
      - opep_0041
      - opep_0042
      - opep_0059
      - opep_0062
      - opep_0063
      - opep_0070
      - opep_0072
      stride: 100
    CATH:
      molecules:
      - cath_2dkzA01
      stride: 100
  batch_sizes:
    OPEP: 37
    CATH: 8
  subsample_random_seed: 42
  max_epoch_samples:
