seed_everything: 16384
trainer:
  auto_lr_find: false
  auto_scale_batch_size: false
  benchmark: false
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        dirpath: default_root_dir
        filename: '{epoch}-{validation_loss:.4f}'
        monitor: validation_loss
        save_last: true
        save_top_k: -1
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 20
  checkpoint_callback: null
  default_root_dir: /data/scratch/gused98/train_output/softmax_exact_favor_cln/2_blocks_128_rbfs_30_opt_eq_priors_proper_nonbond_seed_16384_exact_att_cln
  detect_anomaly: false
  deterministic: false
  enable_checkpointing: true
  enable_progress_bar: false
  strategy: 'ddp_find_unused_parameters_false'
  accelerator: gpu
  devices: 4
  precision: 32
  logger:
  - class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      name: tensorboard
      save_dir: default_root_dir
      version: ''
  max_epochs: 550
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  plugins: null
  precision: 32
  prepare_data_per_node: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: false
  resume_from_checkpoint: null
  stochastic_weight_avg: false
  terminate_on_nan: null
data:
  h5_file_path: /data/scratch/gused98/experiments/softmax_exact_favor_cln/processed_data_opt/cln_delta_dataset.h5
  loading_options:
    hdf_key_mapping:
      coords: cg_coords
      embeds: attrs:cg_embeds
      forces: cg_delta_forces
  partition_options: /data/scratch/gused98/experiments/softmax_exact_favor_cln/processed_data_opt/partition.yaml
model:
  loss:
    class_path: mlcg.nn.Loss
    init_args:
      losses:
      - class_path: mlcg.nn.ForceMSE
        init_args:
          force_kwd: forces
  model:
    class_path: mlcg.nn.GradientsOut
    init_args:
      model:
        class_path: mlcg.nn.schnet.AttentiveSchNet
        init_args:
          activation_func:
            class_path: torch.nn.Tanh
            init_args: {}
          aggr: add
          cutoff:
            class_path: mlcg.nn.CosineCutoff
            init_args:
              cutoff_lower: 0
              cutoff_upper: 30
          embedding_size: 43
          hidden_channels: 128
          max_num_neighbors: 200
          num_filters: 128
          attention_block:
            class_path: mlcg.nn.ExactAttention
          num_interactions: 2
          num_features_in: 128
          num_features_out: 128
          num_residual_k: 1
          num_residual_q: 1
          num_residual_v: 1
          output_hidden_layer_widths:
          - 128
          - 64
          rbf_layer:
            class_path: mlcg.nn.ExpNormalBasis
            init_args:
              cutoff: 30
              num_rbf: 128
              trainable: false
      targets: forces
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
