name: CodeCov
on:
  push:
    branches: [ main ]
  pull_request: # Run on local PRs
    branches: [ main ]
    types: [opened, reopened, synchronize]
  pull_request_target: # Run on fork PRs
    branches: [ main ]
    types: [opened, reopened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    container: nec4/pytorch_geometric_cpu:v1.1
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    # - name: Setup Python
    #   uses: actions/setup-python@master
    #   with:
    #     python-version: 3.8
    - name: Generate Report
      run: |
        pip install coverage pytest
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
